DROP TABLE NETFLIX;
DROP SEQUENCE SEQ_ID;

CREATE TABLE NETFLIX(
    ID VARCHAR2(15) PRIMARY KEY,
    NLEVEL VARCHAR2(30) CHECK(NLEVEL IN('BASIC', 'STANDARD', 'PREMIUM')),
    NICKNAME VARCHAR2(30) NOT NULL,
    SIGNUPDATE DATE DEFAULT SYSDATE,
    POINT NUMBER
);

CREATE SEQUENCE SEQ_ID
NOCACHE;

INSERT INTO NETFLIX VALUES ('abc123', 'BASIC', 'µŒ∏Ææ»', '2021/02/24', 1000);
INSERT INTO NETFLIX VALUES ('eee222', 'BASIC', '≈‰∏¡≈‰', '2021/08/09', 1500);
INSERT INTO NETFLIX VALUES ('rrr555', 'STANDARD', '∏¡∞ÌΩ∫∆æ', '2020/05/25', 2000);
INSERT INTO NETFLIX VALUES ('www999', 'PREMIUM', '¡¶¡÷∞®±÷', '2021/12/25', 3000);

COMMIT;

SELECT * FROM NETFLIX;
SELECT * FROM NETFLIX WHERE ID LIKE '%2%';

INSERT INTO NETFLIX VALUES (?, ?, ?, SYSDATE, ?);
UPDATE NETFLIX SET N_LEVEL = ?, NICKNAME = ?, POINT = ? WHERE ID = ?;