DROP TABLE PRODUCT;

CREATE TABLE PRODUCT(
    PRODUCT_ID VARCHAR2(30) PRIMARY KEY,
    P_NAME VARCHAR2(30) NOT NULL,
    PRICE NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(30),
    STOCK NUMBER NOT NULL
);

COMMENT ON COLUMN PRODUCT.PRODUCT_ID IS '상품아이디';
COMMENT ON COLUMN PRODUCT.P_NAME IS '상품명';
COMMENT ON COLUMN PRODUCT.PRICE IS '상품가격';
COMMENT ON COLUMN PRODUCT.DESCRIPTION IS '상품상세정보';
COMMENT ON COLUMN PRODUCT.STOCK IS '재고';

INSERT INTO PRODUCT VALUES('nd_ss7', '삼성노트북', 1570000, '시리즈7', 10);
INSERT INTO PRODUCT VALUES('nb_ama4', '멕북에어', 1200000, 'xcode4', 20);
INSERT INTO PRODUCT VALUES('pc_ibm', 'ibmPXC', 750000, 'window8', 5);

COMMIT;

SELECT
			  PRODUCT_ID
			, P_NAME
			, PRICE
			, DESCRIPTION
			, STOCK
		 FROM PRODUCT
		WHERE P_NAME LIKE '%노트북%';